version: "3.9"

services:

  tokenizer_service:
    build: ./tokenizer_service
    container_name: tokenizer_service
    ports:
      - "8001:8000"
    restart: always

  embedder_service:
    build: ./embedder_service
    container_name: embedder_service
    ports:
      - "8002:8000"
    restart: always

  grammar_service:
    build: ./grammar_service
    container_name: grammar_service
    ports:
      - "8003:8000"
    restart: always

  lingua_service:
    build: ./lingua_service
    container_name: lingua_service
    ports:
      - "8004:8000"
    restart: always

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"   # Публичный вход
    depends_on:
      - tokenizer_service
      - embedder_service
      - grammar_service
      - lingua_service
