version: "3.9"

services:

  tokenizer_service:
    build: ./tokenizer_service
    container_name: tokenizer_service
    ports:
      - "8001:8000"
    restart: always

  embedder_service:
    build: ./embedder_service
    container_name: embedder_service
    ports:
      - "8002:8000"
    restart: always

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"   # Публичный вход
    depends_on:
      - tokenizer_service
      - embedder_service
